### ISSUE TITLE
Some dimensions produce nightmare fuel (GAN artefacts)

### ISSUE THREAD

**Issue by cdilga** [check-face/checkface#16]
Expected: 
Scaling by any dimension doesn't change the presence of GAN artefacts, and the image would look exactly the same at any dimension. 

Actual result:

https://api.checkface.ml/api/6938e4ed47a23f17ceb6dbd880ab18d2787e7946 and https://api.checkface.ml/api/6938e4ed47a23f17ceb6dbd880ab18d2787e7946?dim=300 is different, as shown

 
![error_checkface](https://user-images.githubusercontent.com/4075815/58749081-87e68a00-84c4-11e9-89ca-d9297fec80fd.png)
![good face](https://user-images.githubusercontent.com/4075815/58749085-8a48e400-84c4-11e9-9c6c-03b881c68c3f.png)

**Comment by olivercoad** [comment]
Updated to stylegan2 which fixes the noise issue, and blob artifacts

Fixed in 7587b532bd6a8acdb93b6b0d84fb38e6d0f001fa
