### ISSUE TITLE
Make landing page more mobile friendly

### ISSUE THREAD

**Issue by olivercoad** [check-face/checkface#22]
The layout of the landing page isn't very good for mobile at the moment.

![image](https://user-images.githubusercontent.com/24837994/63020000-3739d700-bee0-11e9-8135-926d1c66138d.png)

Ideally, one should be able to enter values to the text box, click submit, and view the entire face all without scrolling.

**Comment by cdilga** [comment]
Client should request a smaller image size from the api for mobile. 

Additionally the enter button on mobile will only hide the keyboard if we do a full form submission instead of just replacing the `img src="<url>"` with a new `<url>`
