### ISSUE TITLE
Use Serverless infrastructure for returning images and social preview

### ISSUE THREAD

**Issue by cdilga** [check-face/checkface#30]
We wish to change the current way of rendering social previews using php in the `docs/index.php`  to use a lambda to do this for much cheaper. The costs aren't trivial, though they're not big either.

Additionally, an internal reverse proxy to our on-prem server would mean we can still have an autoscaling group on an ALB but not have to pay for the t2.micro instance running nginx currently.

This blog post has details on how to return images, which proved quite difficult: https://aws.amazon.com/tw/blogs/compute/microservices-without-the-servers/?sc_campaign=blog&sc_category=compute&sc_channel=SM&sc_content=serverless&sc_detail=std&sc_medium=aws&sc_publisher=fb_ln&adbsc=social_blogs_20150909_52150936&adbid=882627328441300&adbpl=fb&adbpr=153063591397681

**Comment by cdilga** [comment]
Code for the Amazon blog post is hosted on github here: https://github.com/silencecork/aws-lambda-api-gateway

**Comment by cdilga** [comment]
While it was difficult to find how lambda was actually handling the request, it seems that sometimes it's hidden inside of the event object. 
Though the event object is specific to the AWS service invoking the lambda.

https://www.taimos.de/blog/rich-social-sharing-using-cloudfront.html

**Comment by cdilga** [comment]
Dubsmash as a particularly relevant implementation that uses no other services: https://engineering.dubsmash.com/how-dubsmash-uses-lambda-edge-to-serve-dynamic-spa-using-s3-1ba865d34512

**Comment by olivercoad** [comment]
Implemeted cloudflare workers to proxy the social links, for e.g. pasting the link `checkface.ml/?value=5` on a social platform will show a opengraph preview.

Implemented by b2cbe9b97860e867bdfc61806ea40a18e5902bd2
