### ISSUE TITLE
Question mark handed incorrectly client side

### ISSUE THREAD

**Issue by cdilga** [check-face/checkface#4]
Current Behavior:
When a question mark is included in the hash, the default dimension of 300 is induced

Expected behavior:
Question marks have no impact on size and the ?dim=500 argument persists regardless of textbox entry

Proposal:
Check how the client side box is sending ? chars and see if it's interfering with the GET request url and causing it to be malformed

**Comment by olivercoad** [comment]
Will need to handle url encoding properly on all clients
