### ISSUE TITLE
Use shared styles in extension

### ISSUE THREAD

**Issue by cdilga** [check-face/checkface#6]
*from [GitLab#13](https://gitlab.com/olivercoad/checkface/issues/13)*

**Comment by cdilga** [comment]
@olivercoad I think this needs some clarification - something to do with style sheets in the chrome extension?

**Comment by olivercoad** [comment]
This issue is refering to the duplication in the stylesheet between the
chrome extension and electron app.

I'm no really sure if it's even a good idea anymore as we may end up
wanting considerable differences between them in the future.

**Comment by cdilga** [comment]
In that case, I think we can close the issue and mark as wontfix
